USE stations;

CREATE TABLE `stations` (

id BIGINT(20) UNSIGNED NOT NULL AUTO INCREMENT,

`name` VARCHAR(50) NOT NULL,

`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT NOW,

`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT NOW,

PRIMARY KEY (id)
    
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

